node:
  name: netology_test

path:
  data: /var/lib/elasticsearch/data
  logs: /var/lib/elasticsearch/logs
  repo:
    - /var/lib/elasticsearch/snapshots

network:
  host: 0.0.0.0

discovery:
  seed_hosts:
    - "127.0.0.1"

cluster:
  initial_master_nodes: 
    - "netology_test"

xpack.security.enabled: false