version: '3.9'

volumes:
  data: {}
  backup: {}

services:
  postgres:
    container_name: postgresql
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - ~/Projects/Netology/postgres/data:/var/lib/postgresql/data
      - ~/Projects/Netology/postgres/backup:/var/lib/postgresql/backup
      - ~/Projects/Netology/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql