version: '3.9'

volumes:
  data: {}

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    volumes:
      - ~/Projects/Netology/mysql/data:/var/lib/mysql
      - ~/Projects/Netology/mysql/test_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - ~/Projects/Netology/mysql/my.cnf:/etc/mysql/my.cnf